# -*- coding: utf-8 -*-
"""simulated_annealing_example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EueyF_rsBUK1LV_HanCiB4YE2XWf4YiA

## Reading Input
"""

import pandas as pd
from proj_utils.input_interpreter import format_input

customer_df = pd.read_excel('data/2_detail_table_customers.xls')
deposit_df = pd.read_excel('data/4_detail_table_depots.xls')
routes = customer_df['ROUTE_ID'].unique()

print(routes)

# Commented out IPython magic to ensure Python compatibility.
from proj_utils.fake_input_generator import generator
from proj_utils.input_interpreter import format_input

import matplotlib.pyplot as plt

from VHR.greedy_solutions import nearest_neighbour_solution
from VHR.modify_solution import combined_rand_modification, crossover_sols
from VHR.verify_solution import valid_path, calculate_path_distance

from proj_utils.path import print_path
# %matplotlib widget

"""# Simulated Annealing Solution"""

import simulated_annealing.solver as SA # Simulated anealing solver

dists, demand, points = format_input(routes[2],customer_df,deposit_df)
#dists, demand, points = generator(20)

solver = SA.generic_solver_factory(
    lambda: nearest_neighbour_solution(dists, demand, (3000,20)),
    lambda x: combined_rand_modification(x, len(points)),
    lambda x: calculate_path_distance(x, dists) if(valid_path(x,(3000,20),demand)) else float('inf'),
    return_history = True
    )

sol,history = solver(200000)

print(history['current_energy'][-1])

print_path(points,sol)

energy_fig, energy_ax = plt.subplots()
energy_ax.plot(history['temperature'],history['current_energy'])
energy_ax.invert_xaxis()
energy_ax.set_title(f"Evolution de la solution du RS pour le route {routes[2]}")
energy_ax.set_xlabel("temperature")
energy_ax.set_ylabel("taille du chemin")

plt.show()
